### ISSUE TITLE
Usability - Docker 

### ISSUE THREAD

**Issue by BakhtawarRehman** [at-wat/cartographer_hokuyo3d#5]
Hello,

This is more like a docker question rather than this library.
I have followed the commands and it's doing absolutely fine.

However, i want to tweak some parameters as the results are not that great for my yvt-x002 lidar. But the problem is that there is no way to edit the configuration files. As i guess they are stored in the image from the docker-hub, thus not on my drive. OR should i use the files from the library and customly define it for my project?

Can someone please guide how to overcome this.

**Comment by at-wat** [comment]
I have added an instruction to apply local changes into the docker container in README.md.
You can easily bind local files into the container.

Also, the command at `Build the image from source` section packs the local changes into the docker image.
In this way, the change in docker-compose.yml is not required. (But need a lot of time to build it.)

**Comment by BakhtawarRehman** [comment]
Hi, Thanks for your time.

But, i think using docker is not an optimal solution as it's taking alot of time and memory on every run.

So; i have decided to use your files within from cartographer workspace (accordingly).

However, i am getting this error, i cannot trace why.

Here is the output [link.](https://docs.google.com/document/d/13LYXR-yTTmGroLbn6au90BLueaSWpWSNPPHqUwBatVU/edit?usp=sharing)

**Comment by at-wat** [comment]
The error is a version difference of the cartographer.
Cartographer is very frequently updated, and the parameters must be updated according to them.
The parameters in this repository are currently for cartographer 0.3.0. (see https://github.com/at-wat/cartographer_hokuyo3d/blob/master/cartographer_hokuyo3d.rosinstall)

> But, i think using docker is not an optimal solution as it's taking alot of time and memory on every run.

Running process inside docker doesn't need extra memory since it is container virtualization, not full virtualization. (Docker daemon uses a small amount, though.)
Only the network and filesystems are separated in the docker container, and Linux kernel is shared with the host.

I'm using docker to avoid such kind of version and dependency issues.

**Comment by BakhtawarRehman** [comment]
I am using the same version of cartographer - 0,30 (same for cartographer_ros) and 1.13.0 ceres solver.
So; version difference here is not an issue.

Yes docker seems cool, but i am definitely much comfortable using it. It already have consumed more than 40GB of space for different builds and i cannot use it fluently.

What'd you suggest for the error problem please?

**Comment by at-wat** [comment]
```
F0405 19:12:48.224817 31211 lua_parameter_dictionary.cc:399] Check failed: HasKey(key) Key 'use_nav_sat' not in dictionary:
```
The error you are facing is saying that the parameter `use_nav_sat` must be set but not set in the configuration file.

This parameter was introduced by https://github.com/googlecartographer/cartographer_ros/pull/659 on Jan 11, 2018, which is a few months later than [0.3.0 released on Nov 23, 2017](https://github.com/googlecartographer/cartographer_ros/releases).
